# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """$character"""
right_format = """$all"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
